### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by GreenMeep0413** [klaymen1n/ddlc-online#1]
Everytime I try to load it, it says: "Error: Uncaught RangeError: Maximum call stack size exceeded (see JavaScript console for details)
This is a known issue in Safari and Webkit browsers. Please report this issue to Apple." Please fix. I'm using a Chromebook btw,

**Comment by klaymen1n** [comment]
Oh, thanks. i have the same error too. I'l look for the reason of that error

**Comment by GreenMeep0413** [comment]
Thank you

**Comment by GreenMeep0413** [comment]
Have you found the reason yet?

**Comment by klaymen1n** [comment]
Fixed now. http://bluka.xyz

**Comment by klaymen1n** [comment]
Oh, it randomly works
