### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by TouhouEngie** [klaymen1n/ddlc-online#3]
The website now only shows the server files.
![image](https://user-images.githubusercontent.com/110212580/184885044-b4fdd725-fc35-4ca2-aa35-a6d6f06099c9.png)

**Comment by TouhouEngie** [comment]
ddlc.bluka.xyz is the website that works, bluka.xyz does not work
also a known issue in webkit browsers is occurring on ms edge
![image](https://user-images.githubusercontent.com/110212580/184924362-5ba792fd-0867-4fe5-8fad-d05bfba4e22a.png)

**Comment by klaymen1n** [comment]
I removed from bluka.xyz site. Now I'm working on another project. Maybe in future I'll fix it. Sorry

**Comment by klaymen1n** [comment]
![Screenshot_2022-08-19-12-08-06-265_org mozilla firefox](https://user-images.githubusercontent.com/84157659/185585811-56f48eb8-4f1d-4563-aea4-7153a3dddc4a.jpg)
But on my phone it's working

**Comment by SmirbYrneh420** [comment]
It was bluka.xyz that shows server files, ddlc.bluka.xyz works fine

**Comment by TouhouEngie** [comment]
I think it was because of firewall on school pc
